box_version = "2021.2.0"

Vagrant.configure(2) do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.box_version = box_version

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "Kali #{box_version}"
    vb.memory = 4096
    vb.cpus = 4
    vb.check_guest_additions = true
    vb.customize ["modifyvm", :id, "--vrde", "off"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

  config.vm.network "forwarded_port", 
    guest: 22, 
    host: 2222

  config.vm.provision "file", 
    source: "~/.ssh/id_rsa.pub", 
    destination: "/home/vagrant/.ssh/authorized_keys"
  
  config.vm.provision "shell",
    inline: "mkdir /root/.ssh && chmod 700 /root/.ssh && cp /home/vagrant/.ssh/authorized_keys /root/.ssh",
    privileged: true
end